// <auto-generated />
using System;
using DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DB.Migrations
{
    [DbContext(typeof(CampaignManagerContext))]
    [Migration("20231110151638_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DB.Models.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CampaignTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Priority")
                        .IsUnique();

                    b.HasIndex("TemplateId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("DB.Models.CampaignCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("CampaignConditions");
                });

            modelBuilder.Entity("DB.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "London"
                        },
                        new
                        {
                            Id = 2,
                            Name = "New York"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Paris"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tel-Aviv"
                        });
                });

            modelBuilder.Entity("DB.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CityDataId")
                        .HasColumnType("int");

                    b.Property<decimal>("Deposit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GenderDataId")
                        .HasColumnType("int");

                    b.Property<bool>("NewCustomer")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CityDataId");

                    b.HasIndex("GenderDataId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 53,
                            CityDataId = 1,
                            Deposit = 104m,
                            GenderDataId = 1,
                            NewCustomer = false
                        },
                        new
                        {
                            Id = 2,
                            Age = 44,
                            CityDataId = 2,
                            Deposit = 209m,
                            GenderDataId = 2,
                            NewCustomer = true
                        },
                        new
                        {
                            Id = 3,
                            Age = 36,
                            CityDataId = 2,
                            Deposit = 208m,
                            GenderDataId = 1,
                            NewCustomer = true
                        },
                        new
                        {
                            Id = 4,
                            Age = 87,
                            CityDataId = 1,
                            Deposit = 134m,
                            GenderDataId = 2,
                            NewCustomer = false
                        },
                        new
                        {
                            Id = 5,
                            Age = 54,
                            CityDataId = 3,
                            Deposit = 123m,
                            GenderDataId = 1,
                            NewCustomer = true
                        },
                        new
                        {
                            Id = 6,
                            Age = 45,
                            CityDataId = 2,
                            Deposit = 210m,
                            GenderDataId = 2,
                            NewCustomer = true
                        },
                        new
                        {
                            Id = 7,
                            Age = 49,
                            CityDataId = 4,
                            Deposit = 174m,
                            GenderDataId = 2,
                            NewCustomer = false
                        },
                        new
                        {
                            Id = 8,
                            Age = 35,
                            CityDataId = 3,
                            Deposit = 52m,
                            GenderDataId = 1,
                            NewCustomer = true
                        },
                        new
                        {
                            Id = 9,
                            Age = 61,
                            CityDataId = 4,
                            Deposit = 151m,
                            GenderDataId = 1,
                            NewCustomer = false
                        },
                        new
                        {
                            Id = 10,
                            Age = 78,
                            CityDataId = 3,
                            Deposit = 57m,
                            GenderDataId = 1,
                            NewCustomer = false
                        },
                        new
                        {
                            Id = 11,
                            Age = 41,
                            CityDataId = 2,
                            Deposit = 131m,
                            GenderDataId = 2,
                            NewCustomer = false
                        },
                        new
                        {
                            Id = 12,
                            Age = 32,
                            CityDataId = 4,
                            Deposit = 154m,
                            GenderDataId = 2,
                            NewCustomer = true
                        },
                        new
                        {
                            Id = 13,
                            Age = 62,
                            CityDataId = 3,
                            Deposit = 135m,
                            GenderDataId = 2,
                            NewCustomer = false
                        },
                        new
                        {
                            Id = 14,
                            Age = 67,
                            CityDataId = 4,
                            Deposit = 153m,
                            GenderDataId = 1,
                            NewCustomer = true
                        },
                        new
                        {
                            Id = 15,
                            Age = 68,
                            CityDataId = 1,
                            Deposit = 241m,
                            GenderDataId = 2,
                            NewCustomer = true
                        },
                        new
                        {
                            Id = 16,
                            Age = 41,
                            CityDataId = 1,
                            Deposit = 134m,
                            GenderDataId = 1,
                            NewCustomer = false
                        },
                        new
                        {
                            Id = 17,
                            Age = 46,
                            CityDataId = 1,
                            Deposit = 212m,
                            GenderDataId = 2,
                            NewCustomer = false
                        },
                        new
                        {
                            Id = 18,
                            Age = 77,
                            CityDataId = 4,
                            Deposit = 97m,
                            GenderDataId = 2,
                            NewCustomer = true
                        },
                        new
                        {
                            Id = 19,
                            Age = 51,
                            CityDataId = 1,
                            Deposit = 141m,
                            GenderDataId = 1,
                            NewCustomer = true
                        },
                        new
                        {
                            Id = 20,
                            Age = 80,
                            CityDataId = 3,
                            Deposit = 189m,
                            GenderDataId = 1,
                            NewCustomer = false
                        },
                        new
                        {
                            Id = 21,
                            Age = 31,
                            CityDataId = 4,
                            Deposit = 134m,
                            GenderDataId = 2,
                            NewCustomer = true
                        },
                        new
                        {
                            Id = 22,
                            Age = 80,
                            CityDataId = 4,
                            Deposit = 81m,
                            GenderDataId = 2,
                            NewCustomer = false
                        },
                        new
                        {
                            Id = 23,
                            Age = 36,
                            CityDataId = 1,
                            Deposit = 237m,
                            GenderDataId = 2,
                            NewCustomer = true
                        },
                        new
                        {
                            Id = 24,
                            Age = 65,
                            CityDataId = 4,
                            Deposit = 119m,
                            GenderDataId = 2,
                            NewCustomer = false
                        },
                        new
                        {
                            Id = 25,
                            Age = 72,
                            CityDataId = 4,
                            Deposit = 139m,
                            GenderDataId = 1,
                            NewCustomer = false
                        },
                        new
                        {
                            Id = 26,
                            Age = 64,
                            CityDataId = 4,
                            Deposit = 128m,
                            GenderDataId = 1,
                            NewCustomer = true
                        },
                        new
                        {
                            Id = 27,
                            Age = 29,
                            CityDataId = 1,
                            Deposit = 76m,
                            GenderDataId = 1,
                            NewCustomer = true
                        },
                        new
                        {
                            Id = 28,
                            Age = 25,
                            CityDataId = 1,
                            Deposit = 203m,
                            GenderDataId = 1,
                            NewCustomer = true
                        },
                        new
                        {
                            Id = 29,
                            Age = 77,
                            CityDataId = 2,
                            Deposit = 54m,
                            GenderDataId = 1,
                            NewCustomer = true
                        },
                        new
                        {
                            Id = 30,
                            Age = 79,
                            CityDataId = 3,
                            Deposit = 165m,
                            GenderDataId = 2,
                            NewCustomer = true
                        },
                        new
                        {
                            Id = 31,
                            Age = 26,
                            CityDataId = 3,
                            Deposit = 143m,
                            GenderDataId = 2,
                            NewCustomer = true
                        },
                        new
                        {
                            Id = 32,
                            Age = 74,
                            CityDataId = 1,
                            Deposit = 61m,
                            GenderDataId = 2,
                            NewCustomer = false
                        },
                        new
                        {
                            Id = 33,
                            Age = 74,
                            CityDataId = 2,
                            Deposit = 103m,
                            GenderDataId = 1,
                            NewCustomer = false
                        },
                        new
                        {
                            Id = 34,
                            Age = 46,
                            CityDataId = 2,
                            Deposit = 121m,
                            GenderDataId = 2,
                            NewCustomer = true
                        },
                        new
                        {
                            Id = 35,
                            Age = 47,
                            CityDataId = 2,
                            Deposit = 214m,
                            GenderDataId = 2,
                            NewCustomer = false
                        },
                        new
                        {
                            Id = 36,
                            Age = 78,
                            CityDataId = 2,
                            Deposit = 111m,
                            GenderDataId = 2,
                            NewCustomer = false
                        },
                        new
                        {
                            Id = 37,
                            Age = 46,
                            CityDataId = 2,
                            Deposit = 223m,
                            GenderDataId = 2,
                            NewCustomer = true
                        },
                        new
                        {
                            Id = 38,
                            Age = 26,
                            CityDataId = 2,
                            Deposit = 78m,
                            GenderDataId = 2,
                            NewCustomer = true
                        },
                        new
                        {
                            Id = 39,
                            Age = 49,
                            CityDataId = 4,
                            Deposit = 60m,
                            GenderDataId = 2,
                            NewCustomer = false
                        },
                        new
                        {
                            Id = 40,
                            Age = 74,
                            CityDataId = 2,
                            Deposit = 53m,
                            GenderDataId = 2,
                            NewCustomer = true
                        });
                });

            modelBuilder.Entity("DB.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gender");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Male"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Female"
                        });
                });

            modelBuilder.Entity("DB.Models.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Template");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "TemplateA",
                            Url = "Resources/Templates/Resources/Templates/TemplateA.html"
                        },
                        new
                        {
                            Id = 2,
                            Name = "TemplateB",
                            Url = "Resources/Templates/Resources/Templates/TemplateB.html"
                        },
                        new
                        {
                            Id = 3,
                            Name = "TemplateC",
                            Url = "Resources/Templates/Resources/Templates/TemplateC.html"
                        });
                });

            modelBuilder.Entity("DB.Models.Campaign", b =>
                {
                    b.HasOne("DB.Models.Template", "TemplateData")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemplateData");
                });

            modelBuilder.Entity("DB.Models.CampaignCondition", b =>
                {
                    b.HasOne("DB.Models.Campaign", null)
                        .WithMany("CampaignConditions")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DB.Models.Customer", b =>
                {
                    b.HasOne("DB.Models.City", "CityData")
                        .WithMany()
                        .HasForeignKey("CityDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB.Models.Gender", "GenderData")
                        .WithMany()
                        .HasForeignKey("GenderDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CityData");

                    b.Navigation("GenderData");
                });

            modelBuilder.Entity("DB.Models.Campaign", b =>
                {
                    b.Navigation("CampaignConditions");
                });
#pragma warning restore 612, 618
        }
    }
}
